version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=person_db'
      - 'POSTGRES_PASSWORD=secret123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  people-service:
    image: people-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
